# Railway Deployment Configuration
services:
  web:
    build:
      dockerfile: Dockerfile.deploy
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - PORT=8000
      - STREAMLIT_SERVER_PORT=8501
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/", "&&", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"